### ISSUE TITLE
Allow rusk to be compiled with different setups

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/rusk#1144]
#### Summary
A node should be compiled to be:
- Full Node 
- Provisioning Node
- Prover only

#### Possible solution design or implementation
N/A

#### Prerequisites
- [x] Prover module should be behind a feature flag. #1145 
- [ ] Add events store (for Full Node).
- [ ] Add archival functionality https://github.com/dusk-network/rusk/issues/1684

#### Additional context
N/A

**Comment by HDauven** [comment]
Related issue: #1058

**Comment by ureeves** [comment]
I notice that this is missing the role of an "archiver", a role much discussed in the past. Interestingly, we just [dismissed a PR](https://github.com/dusk-network/rusk/pull/1513) that was very much making inroads in implementing such a role. I will add it to the list on the comment above.

**Comment by HDauven** [comment]
Closing as obsolete epic
