### ISSUE TITLE
[EPIC] Performance Improvements

### ISSUE THREAD

**Issue by Fulviuus** [dusk-network/rusk#1301]
# Epic

## Summary

This Epic will be a collection of fixes required to address the various performance issues currently afflicting the first release of the Web Wallet.

The two major areas of performance improvements we can work on are the `synchronization` with the node, and the `WebAssembly` execution.

## Tasks

- [x] dusk-network/exu#1
- [x] dusk-network/dusk-wallet-js#11
- [x] #1286 
- [x] https://github.com/dusk-network/exu/issues/3

**Comment by nortonandreev** [comment]
Can this be closed now? cc: @Daksh14

**Comment by Daksh14** [comment]
@nortonandreev There's always room for improvement, I'd say keep it open and we add more issues here.

**Comment by HDauven** [comment]
> here's always room for improvement, I'd say keep it open and we add more issues here.

That's not how an epic works. It's not a queue of upcoming issues, that's why we create new issues. Closing
