### ISSUE TITLE
[EPIC] Code Maintenance

### ISSUE THREAD

**Issue by Fulviuus** [dusk-network/rusk#1302]
# Epic

Maintenance tasks to make the wallet codebase more solid

## Stories

- [x] dusk-network/web-wallet#383
- [x] dusk-network/web-wallet#429 
- [x] dusk-network/rusk#1312
