### ISSUE TITLE
[EPIC] Community feedback

### ISSUE THREAD

**Issue by deuch13** [dusk-network/rusk#1303]
# Epic

Handle issues raised by the community in order to improve the wallet.

## Tasks

- [x] dusk-network/web-wallet#369 
- [x] dusk-network/web-wallet#382
- [x] dusk-network/web-wallet#379
- [x] Suggestion: Add ability to revert one word at a time during the setup/restore flows _(Tracked under dusk-network/rusk#1290 – possibly blocked on dusk-network/rusk#1302)_
