### ISSUE TITLE
[EPIC] Web wallet migration to public repository

### ISSUE THREAD

**Issue by Fulviuus** [dusk-network/rusk#1307]
### Description ###

We are making our web-wallet repository public.
Here is a list of actions to be performed to complete the move:

- [ ] Review every file in the current codebase to identify any elements that could impact our security. This includes comments, hardcoded variables, environment naming, or similar aspects. For instance, the staking tab can be activated by modifying an environment variable. What implications might this have for security? In our case, probably none, but we need to consider such scenarios. **[team]**
- [ ] Obtain approval from the team after completing the above task. **[fulvio]**
- [ ] Create a new, clean repository under `dusk-network`. Clone the current repository, delete the `.git` folder, and commit and push into the new repository. **[fulvio]**
- [ ] Modify the repository rules to align with those of the organization's other public repositories, such as mandating reviews and approvals prior to merging pull requests, among other requirements. **[fulvio]**
- [ ] Transfer all active issues from `web-wallet` to the new repository. **[fulvio]**

> [!NOTE]  
> Signoff from **all** team members is required before proceeding with the creation of the new repository.

|  Team Member  |  Signoff  |
|----------------|-----------| 
| Fulvio         |   no      |
| Matteo         |   no      |
| Kieran         |   no      |
| Andrea         |   no      |
| Norton         |   no      |
| Alex           |   no      |
| Daksh          |   no      |

> [!IMPORTANT]  
> Issues identified during the code review will be added below:

[No issues currently found]
