### ISSUE TITLE
[EPIC] Allow users to sync from a specific block height 

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1521]
# Optimize performance by allowing users to sync from a specific block height 

## Summary

Currently, creating / restoring a Wallet takes a long time, dependent on the blockchain size. We should aim to optimize performance by allowing users to sync from the point when the user's wallet has been created.

This epic captures all the requirements and the work needed to fulfill this initiative.

## Requirements [WIP]
- [ ] We should make sure to display the current block height on Wallet creation
- [ ] We should let users specify block height to sync from on Wallet restoration (with appropriate notice)
- [ ]  We should allow users to sync from the genesis, if needed (Advanced option)

Each requirement needs a design, as well as making sure we have the APIs on the service side, dusk-wallet-js (eg. for setting the height to sync from, to receive the current height, etc).

## Tasks [TBC]
_Will be created once the requirements have been signed off._

## Benefits

Syncing a cryptocurrency wallet from a specific block height, instead of from the genesis block, offers several benefits, such as: faster synchronization, reduced storage requirements, lower bandwidth usage, and enhanced accessibility.

**Comment by ZER0** [comment]
This is what Monero does: https://www.getmonero.org/resources/user-guides/change-restore-height.html#what-is-the-wallet-restore-height

**Comment by nortonandreev** [comment]
> This is what Monero does: https://www.getmonero.org/resources/user-guides/change-restore-height.html#what-is-the-wallet-restore-height

Lovely, thank you! Was looking for this info. To sum up, Monero:

- suggests the custom block height should be the number of the block which included the first incoming transaction to your wallet
- if unsure of the block height, suggests entering a lower restore height instead of a higher one (so that transactions are not missed)
- supports a date – apart from the block height (I think this is useful, as users might not remember the block height, but instead might have an estimated date on when they have created their wallet)

![set_new_restore_height-date](https://github.com/dusk-network/rusk/assets/34094428/aec817f9-af38-417f-8122-53157ec9cde4)

- has the block height as a setting – changing the height will trigger a resync (and rebuilding of the Wallet's cache)

![change_wallet_restore_height](https://github.com/dusk-network/rusk/assets/34094428/179efcd8-5765-403d-8368-dd98a6a590cc)

![rescan_wallet_cache](https://github.com/dusk-network/rusk/assets/34094428/4058a6e1-4129-4c98-89a9-7d26dfcccb83)
