### ISSUE TITLE
Implement Phoenix 2.0

### ISSUE THREAD

**Issue by xevisalle** [dusk-network/rusk#1677]
# Epic

## Summary

Phoenix 2.0 should be implemented in Rusk. To do so, the following tasks need to be addressed:

## Tasks

- [x] https://github.com/dusk-network/rusk/issues/1675
- [x] https://github.com/dusk-network/rusk/issues/1609
- [ ] https://github.com/dusk-network/rusk/issues/1676

**Comment by autholykos** [comment]
Closed as we are tracking the issues using the appropriate project in the Protocol board
