### ISSUE TITLE
Prepare for arbitrary smart contract deployment

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#1689]
# Epic

## Summary

Allow for the deployment of smart contracts beyond genesis.

## Tasks

*List related tasks and their issue numbers.*

- [x] dusk-network/rusk#1071
- [x] dusk-network/docs#74
- [ ] https://github.com/dusk-network/piecrust/issues/351 (Optionally, introduce a feature flag that allows us to enable deployments later on)
