### ISSUE TITLE
Implement new market data API and logic

### ISSUE THREAD

**Issue by ascartabelli** [dusk-network/rusk#1829]
#### Summary

The public coin gecko API has a "stable rate limit of 30 calls/min and a monthly cap of 10,000 calls", so with the updates to polling logic that we made in https://github.com/dusk-network/rusk/issues/1835, we can setup components to poll the market data every two minutes and be on the safe side regarding the API caps.

- Components using the market data should be updated to use polling
- Remove the market data fetch on network change, as such data is not dependent on the node
- If the coin gecko API returns an error (actual error or because of exceeded cap limit) we should show the last good result, if any, and let the user know that he's looking at stale data (@laremas).

- [x] https://github.com/dusk-network/rusk/issues/1890
- [x] https://github.com/dusk-network/rusk/issues/1891
- [x] https://github.com/dusk-network/rusk/issues/1913
- [x] https://github.com/dusk-network/rusk/issues/1892

#### Additional notes
With @ZER0 we talked about having a more complicated mechanism in place to limit the risk of reaching the API caps even further. 
We also decided to not implement any of the following in the first iteration and first observe if any problem arises with the simple implementation.
A possible idea is as follows:

- if the coin gecko API will allow us to know how many calls we have left before reaching the limit, we can dynamically change the poll rate and slow it down to stay in the limits
- use, for example, local storage as a single source of truth for market data so that it can be shared by both the explorer and the web-wallet as they are running on the same domain. By using a lock mechanism such as looking at the timestamp of the last call, an application knows if it should make a call to the API or wait for the local storage to be updated by the other application.

**Comment by ascartabelli** [comment]
Closing as all sub-tasks are completed
