### ISSUE TITLE
Reset and Upgrade Nocturne testnet

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#2108]
#### Summary

Our current testnet, Nocturne, hasn't been upgraded since ITN concluded. Nocturne should incorporate the latest changes and improvements.

#### Tasks

- [x] Update public documentation on Nocturne
- [x] Update our [node-installer](https://github.com/dusk-network/node-installer)
- [x] Reset & upgrade our public testnet Nocturne 
- [x] Communicate the reset & upgrade of Nocturne

**Comment by HDauven** [comment]
Resolved by the Nocturne reset at October 2nd: https://dusk.network/news/mainnet-milestone-nocturne-is-live/
