### ISSUE TITLE
Improve fetch_notes performance

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/rusk#2513]
#### Summary
With dusk-network/wallet-cli#147 the fetch_notes has been changed to check the ownership o a note against all the addresses createable (up to MAX_ADDRESSES=255).
Even if this lead to a boost performance improvement while switching address, it lead to an overall bottleneck when the wallet has only a few address.

#### Possible solution design or implementation
This can be mitigated with these changes:
- [ ] Perform the check against all created addresses (instead of MAX_ADDRESSES) dusk-network/wallet-cli#168
- [ ] Only while recovering the wallet from a seed, still perform a check against all MAX_ADDRESSES dusk-network/wallet-cli#80
- [ ] Parallelization of checking notes tasks dusk-network/wallet-cli#160 

#### Additional context
Currently, checking a note for all the 255 addresses tooks ~60ms on Apple M1

```
Ownership for address #0- Elapsed 242.541µs
Check for address #0- Elapsed 243.333µs
[.....]
Ownership for address #253- Elapsed 242.458µs
Check for address #253- Elapsed 243.25µs
Ownership for address #254- Elapsed 245.25µs
Check for address #254- Elapsed 247.125µs
------------------------------------
Check all addresses in 62.947208ms
```
