### ISSUE TITLE
Replace failure::Error and use Anyhow::Error

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/rusk#39]
We are currently using this in:
- [x] Plonk - https://github.com/dusk-network/plonk
- [x] dusk-blindbid - https://github.com/dusk-network/dusk-blindbid
- [x] phoenix-core - https://github.com/dusk-network/phoenix-core
- [x] Poseidon252 - https://github.com/dusk-network/Poseidon252
- [x] dusk-pki - https://github.com/dusk-network/dusk-pki
The `failure` crate has been deprecated and they recommend to use https://github.com/dtolnay/anyhow as a replacement for generic Errors built on top of `std::err::Err`.

So we should migrate the aforementioned libraries to the `Anyhow::Error` type.

**Comment by CPerezz** [comment]
Phoenix-core also comes with `anyhow`. 

This means that we successfully completed the migration. And therefore, this can be closed.
