### ISSUE TITLE
Create smart contract documentation

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#870]
# Epic - Create 

## Summary

Create comprehensive and well-structured documentation for the Piecrust smart contract platform to enable third-party developers to easily understand, build and deploy smart contracts while ensuring they follow best practices and are aware of any platform caveats.

## Tasks

- [ ] Write an intro to the smart contract platform
- [ ] Develop a getting started guide
- [ ] Create a detailed language guide covering syntax, available types and structures
- [ ] Describe common smart contracts, use cases and best practices
- [ ] Document contract modules and libraries, including host functions
- [ ] Provide guidance on testing and debugging
- [ ] Explain deployment and migration strategies for smart contracts
- [ ] Dive into advanced topics like custom circuits and optimizations
- [ ] Compile community and support resources
- [ ] Create a comprehensive API reference

## Benefits

This epic will provide developers with a clear understanding of how smart contracts work in the context of Dusk, making it easier for them to get started, build, test and deploy smart contracts. It will also be a way to promote best practices and security guidelines, ensuring the overall quality of Dusk contracts Well-structured and good documentation will foster a strong developer community, encouraging adoption of the platform.

**Comment by HDauven** [comment]
On review, double check the documentation with our current community devs and our newly added dev advocate.
