### ISSUE TITLE
Implement a contract-driven fee market

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#880]
#### Summary
Contracts should be able to choose how fees are paid for the execution of their code.

#### Detailed Description
Currently, while a transaction is being executed, the computational resources it consumes are metered and then charged to the user, who agrees on a `gas limit` and a `gas price` when producing the transaction.

The amount charged, together with the coinbase, is then awarded to both the block generator (90%) and Dusk (10%).

This proposal seeks to augment this functionality by allowing [contract owners](https://github.com/dusk-network/piecrust/issues/158) to:

* [ ] Be rewarded for execution of their code by allowing them to levy an additional fee on a transaction [#881]
* [ ] Comp the user's gas fee for execution of their code [#882]

In this context we will also require:

* [x] Upgrade `piecrust` version to allow for contract ownership [#883]

### Additional Context
Allowing contracts to both levy and comp fees opens up a market for contract writers. The properties of this market, and its game-theoretical implications require investigation.

**Comment by Mzer0ni** [comment]
Additional point for investigation I like to see is regarding end-user flow. How will a transactor be able to learn, before transacting, what fee system applies. What system can be used so that wallets you access or derive this info and visualise it to users ?
